import { gql } from 'react-apollo';

export default gql`
  query Quote($token: String!) {
    quote(token: $token) {
      id
      NDA
      platforms{
        web
        android
        ios
        desktop
      }
      pages
      design
      authentication{
        email
        social
      }
      data{
        database
        media
        datasource
      }
      geolocation{
        simple
        advanced
      }
      communication{
        chat
        email
        push
        sms
      }
      apis
      commerce{
        basicTransactions
        advancedTransactions
        basicSubscriptions
        advancedSubscriptions
      }
      admin{
        admin
        dashboard
        reports
      }
      product{
        prototype
        mvp
        polished
      }
      time{
        normal
        asap
        now
      }
      plan{
        payg
        installments
        fee
      }
      prices{
        payg
        installments
        fee
      }
      comments
      name
      email
      saved
    }
  }
`;
